app = "sintergia"

[build]
  dockerfile = "DockerFile"

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[services]
  min_machines_running = 1  # This will keep at least one machine running